### ISSUE TITLE
firefox - Error: HTTP method not allowed

### ISSUE THREAD

**Issue by lar-dragon** [gemini-testing/hermione#473]
После инициализации тестов для Firefox падает ошибка 405 при попытке [получить позицию элемента](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidlocation) даже если нет ассертов.

Конфигурация docker-compose для GRID:

```yml
grid:
  image: selenium/hub
  environment:
    - GRID_MAX_SESSION=25
    - JAVA_OPTS=-Xmx128m
  ports:
    - "4444:4444"

firefox:
  image: selenium/node-firefox
  environment:
    - HUB_HOST=grid
    - HUB_PORT=4444
    - NODE_MAX_INSTANCES=25
    - NODE_MAX_SESSION=25
    - JAVA_OPTS=-Xmx128m
  depends_on:
    - grid
```

Браузер в `.hermione.conf.js`:

```js
firefox: {
  desiredCapabilities: {
    browserName: 'firefox',
    args: [
      '--no-sandbox',
      '--headless',
    ],
    windowSize: {
      width: 800,
      height: 600,
    },
  },
},
```

Стектрейс:

```
Error: HTTP method not allowed
    at new RuntimeError (/opt/app/node_modules/@gemini-testing/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/opt/app/node_modules/@gemini-testing/webdriverio/build/lib/utils/RequestHandler.js:306:39)
    at Request.self.callback (/opt/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Request.<anonymous> (/opt/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at IncomingMessage.<anonymous> (/opt/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
